remove bun tests for now

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -70,18 +70,18 @@ jobs:
       - name: Lint
         run: deno run -A ./eng/tasks/main.ts lint --all
         
-      - name: Test Bun
-        shell: bash
-        run: |
-          set +o pipefail # Disable pipefail to avoid failing on warnings
-          bun test 
-          ec=$?
+      #- name: Test Bun
+      #  shell: bash
+      #  run: |
+      #    set +o pipefail # Disable pipefail to avoid failing on warnings
+      #    bun test 
+      #    ec=$?
           # bun fails occassionally using node:test because "test inside of test" is not supported"
-          if [ $ec -ne 0 ]; then
-            echo "\e[33mBun tests failed, but continuing...\e[0m"
-            exit 0
-          fi
-        working-directory: npm
+      #    if [ $ec -ne 0 ]; then
+      #      echo "\e[33mBun tests failed, but continuing...\e[0m"
+      #      exit 0
+      #    fi
+      #  working-directory: npm
 
       - name: Test Node
         run: node --test
